import mongoose from 'mongoose';

export default [{
  _id: mongoose.Types.ObjectId('628947336a58a75cb236a211'),
  firstName: 'Joseph',
  lastName: 'Joestar',
  password: '1234abcd',
  role: 'SA',
  email: 'jo.jo@swfoundation.com',
  active: true,
},
{
  _id: mongoose.Types.ObjectId('62894865e637467db9f844cc'),
  firstName: 'Giorno',
  lastName: 'Giovanna',
  password: '1t4r14',
  role: 'SA',
  email: 'golden.w@ventoaureo.com',
  active: true,
},
{
  _id: mongoose.Types.ObjectId('628a527fcf385c8f4627df3c'),
  firstName: 'Dio',
  lastName: 'Brando',
  password: 'Zaw4rud0',
  role: 'SA',
  email: 'dio.muda@konodda.com',
  active: false,
},
{
  _id: mongoose.Types.ObjectId('628a8fffd8b5e6f80dc11868'),
  firstName: 'Bruno',
  lastName: 'Bucciarati',
  password: 'Z1pp3rm4n',
  role: 'SA',
  email: 'bucciarati.bruno@passione.com',
  active: false,
},
{
  _id: mongoose.Types.ObjectId('628a97f07102b9d99e4dc718'),
  firstName: 'Okuyasu',
  lastName: 'Nijimura',
  password: 'Tr1ll1on',
  role: 'SA',
  email: 'oku.nij@hando.com',
  active: true,
}];
