import mongoose from 'mongoose';

export default [
  {
    id: mongoose.Types.ObjectId('6289ab61fc13ae770a000000'),
    nameProject: 'Edgeify',
    week: 38,
    day: 1,
    description: 'ut massa volutpat convallis morbi odio odio elementum eu interdum eu tincidunt in leo',
    hours: 78,
  },
  {
    id: mongoose.Types.ObjectId('6289ab61fc13ae770a000001'),
    nameProject: 'Oyoyo',
    week: 34,
    day: 2,
    description: 'tortor id nulla ultrices aliquet maecenas leo odio condimentum id luctus nec molestie',
    hours: 19,
  },
  {
    id: mongoose.Types.ObjectId('6289ab61fc13ae770a000002'),
    nameProject: 'Wikizz',
    week: 45,
    day: 3,
    description: 'libero nullam sit amet turpis elementum ligula vehicula consequat morbi a ipsum integer',
    hours: 46,
  },
  {
    id: mongoose.Types.ObjectId('6289ab61fc13ae770a000003'),
    nameProject: 'Meedoo',
    week: 11,
    day: 4,
    description: 'nulla nunc purus phasellus in felis donec semper sapien a libero nam dui proin leo odio',
    hours: 15,
  },
  {
    id: mongoose.Types.ObjectId('6289ab61fc13ae770a000004'),
    nameProject: 'Fliptune',
    week: 8,
    day: 5,
    description: 'dis parturient montes nascetur ridiculus mus etiam vel augue vestibulum',
    hours: 9,
  },
  {
    id: mongoose.Types.ObjectId('6289ab61fc13ae770a000005'),
    nameProject: 'Zoombox',
    week: 38,
    day: 6,
    description: 'mauris eget massa tempor convallis nulla neque libero convallis eget eleifend luctus',
    hours: 55,
  },
  {
    id: mongoose.Types.ObjectId('6289ab61fc13ae770a000006'),
    nameProject: 'Twitterbridge',
    week: 16,
    day: 7,
    description: 'tristique in tempus sit amet sem fusce consequat nulla nisl nunc nisl',
    hours: 44,
  },
  {
    id: mongoose.Types.ObjectId('6289ab61fc13ae770a000007'),
    nameProject: 'Edgeblab',
    week: 15,
    day: 8,
    description: 'cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus vivamus',
    hours: 76,
  },
  {
    id: mongoose.Types.ObjectId('6289ab61fc13ae770a000008'),
    nameProject: 'Thoughtblab',
    week: 5,
    day: 9,
    description: 'nibh quisque id justo sit amet sapien dignissim vestibulum vestibulum ante ipsum primis',
    hours: 23,
  },
  {
    id: mongoose.Types.ObjectId('6289ab61fc13ae770a000009'),
    nameProject: 'Fliptune',
    week: 38,
    day: 10,
    description: 'quisque id justo sit amet sapien dignissim vestibulum vestibulum ante ipsum',
    hours: 46,
  },
];
